[package]
name = "mqtt-broker"
version = "0.1.0"
authors = ["Mike Yagley <myagley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mqtt = { git = "https://github.com/myagley/mqtt", branch = "v0.2.x" }
